### ISSUE TITLE
Feature Request: Availability via homebrew

### ISSUE THREAD

**Issue by vifi42** [jacklandrin/OnlySwitch#1]
I think a lot of people, including me, would LOVE if this was installable via hombrew :)

**Comment by jacklandrin** [comment]
Thank you for your suggestion! I'll add homebrew install to my todo list.

**Comment by jacklandrin** [comment]
> I think a lot of people, including me, would LOVE if this was installable via hombrew :)

Sorry for long time wait. Recently, I tried to publish OnlySwitch by homebrew, but there's an error said "GitHub repository too new (<30 days old)". So, I think you need to continue waiting in serval days.

**Comment by jacklandrin** [comment]
> I think a lot of people, including me, would LOVE if this was installable via hombrew :)

It's available. brew install only-switch
