### ISSUE TITLE
Not working properly on Macos 14.

### ISSUE THREAD

**Issue by xilu-wang** [jacklandrin/OnlySwitch#102]
**Describe the bug**
Not working properly on Macos 14. can't see the small icon on the menu bar.

**To Reproduce**
1. load app

**Screenshots**

<img width="753" alt="Screenshot 2023-11-22 at 09 15 05" src="https://github.com/jacklandrin/OnlySwitch/assets/15312906/79da6e23-3ef0-41dd-b372-d680e493ba33">

**Desktop (please complete the following information):**
 - OS: macos 14

**Comment by jacklandrin** [comment]
Hi @xilu-wang 
Thanks for the feedback. 
Can you confirm if you enabled this feature here?
<img width="924" alt="Screenshot 2023-11-22 at 18 17 50" src="https://github.com/jacklandrin/OnlySwitch/assets/3782279/b95137d7-6527-4446-9c5d-7889f883dea7">

**Comment by jacklandrin** [comment]
Hi @xilu-wang,
Can you explain which icon disappears? OnlySwitch icon or separation icon?
If you can't see OnlySwitch icon, please check if there is a conflict between OnlySwitch and hidebar. If you can't see separation icon, please check if you have enabled Hide Menu Bar Icon like this:
<img width="924" alt="Screenshot 2023-11-22 at 18 17 50" src="https://github.com/jacklandrin/OnlySwitch/assets/3782279/19da5591-d78a-4ed3-9097-c6b64da3b212">
