### ISSUE TITLE
Now Playing Always Showing

### ISSUE THREAD

**Issue by rabbly** [jacklandrin/OnlySwitch#103]
**Describe the bug**
"Now Playing" menu icon always appears with Only Switch listed

**To Reproduce**
1. Enable Only Switch
2. See that the "Now Playing" menu icon automatically appears, with Only Switch as the "Now Playing" list

**Expected behavior**
Now Playing should now show for Only Switch

**Screenshots**
<img width="300" alt="image" src="https://github.com/jacklandrin/OnlySwitch/assets/2348746/0d359592-b20f-48cb-8f0c-e74d1d740fdc">

**Desktop (please complete the following information):**
 - OS: Sonoma
 - Version: v2.4.6

**Comment by jacklandrin** [comment]
The only way is going to Settings -> Customize to disable Radio Player

**Comment by rabbly** [comment]
Perfect, that works - it wasn't clear that was why it was showing 😀

**Comment by drewbitt** [comment]
@jacklandrin is it actually required for a MacOS app to immediately take over Now Playing upon launch if it has an ability to play an audio track? Is it not possible to hijack it after the user plays something first?
