### ISSUE TITLE
Can't select Desktop-Icons while using mission control

### ISSUE THREAD

**Issue by noestreich** [jacklandrin/OnlySwitch#11]
Strange Behavior while using Mission Control:
If OnlySwitch is running and i use Command+F3 or the four finger trackpad gesture (or, in my case an active corner with the mouse) to show the desktop. I cant' select any Icons on the desktop with the mouse anymore. If i close OnlySwitch, everything is fine again.

**Comment by jacklandrin** [comment]
Thank you for your feedback. I'll fix it in next version.

**Comment by jacklandrin** [comment]
The version 1.8.1 has published.  Please check.

**Comment by noestreich** [comment]
Great. Fixed!
