### ISSUE TITLE
Slovak localisation

### ISSUE THREAD

**Issue by Svec-Tomas** [jacklandrin/OnlySwitch#116]
Hey! Please find attached here the Slovak translation of Only Switch.
[OnlySwitch.zip](https://github.com/jacklandrin/OnlySwitch/files/13876415/OnlySwitch.zip)

**Comment by jacklandrin** [comment]
[Only Switch_beta.dmg.zip](https://github.com/jacklandrin/OnlySwitch/files/13879095/Only.Switch_beta.dmg.zip)

**Comment by Svec-Tomas** [comment]
I have checked and fixed everything. Now the translation is good and ready to be added to public release.
[Only Switch Slovak.zip](https://github.com/jacklandrin/OnlySwitch/files/13880832/Only.Switch.Slovak.zip)


Thanks!
