### ISSUE TITLE
希望深色模式可以根据日出日落来自动开关

### ISSUE THREAD

**Issue by Stanley-baby** [jacklandrin/OnlySwitch#121]
**Is your feature request related to a problem? Please describe.**
希望深色模式的一些建议：
- 根据日出日落自动开关
- 自定义时间开启关闭

**Comment by jacklandrin** [comment]
感谢建议！
* 关于日出日落自动开关，由于相关API是由苹果WeatherKit，但是这个库是收费的，所以并未添加此功能。除非以后考虑做会员功能。https://developer.apple.com/weatherkit/get-started
* 未来打算给所有开关都做一个自定义时间功能，但是还没有想好UX设计，所以可能要等一等。

**Comment by Stanley-baby** [comment]
可以做一个自定义时间开关功能，然后哪一个快捷功能需要使用这个时间开关就拖进去，这个就可以自定义某一个快捷功能使用时间开关了，期待！

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: jack ***@***.***>
发送时间: Sunday, February 18, 2024 6:33:49 PM
收件人: jacklandrin/OnlySwitch ***@***.***>
抄送: Stanley-baby ***@***.***>; Author ***@***.***>
主题: Re: [jacklandrin/OnlySwitch] 希望深色模式可以根据日出日落来自动开关 (Issue #121)


感谢建议！

  *   关于日出日落自动开关，由于相关API是由苹果WeatherKit，但是这个库是收费的，所以并未添加此功能。除非以后考虑做会员功能。https://developer.apple.com/weatherkit/get-started
  *   未来打算给所有开关都做一个自定义时间功能，但是还没有想好UX设计，所以可能要等一等。

―

**Comment by jacklandrin** [comment]
现在其实有两种时间任务：
1. 定时任务。过了一定时间之后，开启开关。例如：1min之后，屏幕变暗
2. 每日计划。例如：从早晨8点到晚上6点，开关开启，其余时间是关闭的
目前OnlySwitch不仅有开关，还有一些按钮。对于按钮来讲只有定时任务，没有每日计划。
而且不是所有开关都适合加入自定义时间的，可能需要有个例外的列表，比如番茄时钟本来就是个基于timer的功能。
此外，我还希望时间认为可以支持快捷指令和Evolution。
所以这个我也考虑了很长时间该如何实现。

**Comment by Stanley-baby** [comment]
非常期待！٩(•̤̀ᵕ•̤́๑)ᵒᵏᵎᵎᵎᵎ

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: jack ***@***.***>
发送时间: Sunday, February 18, 2024 6:53:00 PM
收件人: jacklandrin/OnlySwitch ***@***.***>
抄送: Stanley-baby ***@***.***>; Author ***@***.***>
主题: Re: [jacklandrin/OnlySwitch] 希望深色模式可以根据日出日落来自动开关 (Issue #121)


现在其实有两种时间任务：

  1.  定时任务。过了一定时间之后，开启开关。例如：1min之后，屏幕变暗
  2.  每日计划。例如：从早晨8点到晚上6点，开关开启，其余时间是关闭的
目前OnlySwitch不仅有开关，还有一些按钮。对于按钮来讲只有定时任务，没有每日计划。
而且不是所有开关都适合加入自定义时间的，可能需要有个例外的列表，比如番茄时钟本来就是个基于timer的功能。
此外，我还希望时间认为可以支持快捷指令和Evolution。
所以这个我也考虑了很长时间该如何实现。
