### ISSUE TITLE
Icon as battery

### ISSUE THREAD

**Issue by kopach** [jacklandrin/OnlySwitch#123]
**Is your feature request related to a problem? Please describe.**
OnlySwitch unnecessarily adds extra icon to top bar. There is no way to also hide/remove native similar icon, therefore we have 2 almost identical icons
![image](https://github.com/jacklandrin/OnlySwitch/assets/8749624/1c60bf91-87f1-49a6-97ca-b2e19891ebcf)

**Describe the solution you'd like**
Most of the time I need battery icon only to see battery level and whether laptop is charging I never actually click on that native battery Icon.
We could get use of this fact and make OnlySwitch to show battery level & charging status (same way as native icon does this). 
Native battery icon then could be removed from top bar

**Describe alternatives you've considered**
hide only switch and use shortcuts only, which is not that useful, so don't know

**Comment by kopach** [comment]
ok, actually found "buttery" like icon, but it doesn't show charging status/battery level
![image](https://github.com/jacklandrin/OnlySwitch/assets/8749624/4a5e93d4-a379-4814-bdc3-c0e0db36a6d9)

**Comment by jacklandrin** [comment]
Thank you for your idea!
I haven't planned to develop a battery icon instead of switch icon since I don't think the battery percent is relative to switches feature. I can recommend you to use [eul](https://github.com/gao-sun/eul) as a battery icon, it also integrates many performance information.
