### ISSUE TITLE
台前调度与隐藏桌面程序的冲突

### ISSUE THREAD

**Issue by Similarityoung** [jacklandrin/OnlySwitch#124]
**Describe the bug**
当我使用小组件的隐藏桌面程序时，点击桌面空白处并不会显示桌面
但我设置了
<img width="465" alt="image" src="https://github.com/jacklandrin/OnlySwitch/assets/94664304/e41f7e24-1292-45be-966c-efef44622277">

并且恢复桌面程序后
<img width="865" alt="image" src="https://github.com/jacklandrin/OnlySwitch/assets/94664304/afc72329-2205-4403-9737-697f259cda18">
我在打开以下按钮的情况下，App 依然会隐藏
<img width="459" alt="image" src="https://github.com/jacklandrin/OnlySwitch/assets/94664304/32eb3c27-a7f0-47a5-817b-a95249d1e5a0">

**Expected behavior**
希望使用隐藏桌面图标时，可以点击墙纸返回桌面。并且恢复桌面图标时，不会隐藏 App。

**Desktop (please complete the following information):**
 -<img width="191" alt="image" src="https://github.com/jacklandrin/OnlySwitch/assets/94664304/bb0dcd8c-19c4-411a-9dc2-62f0228ec7a3">

**Comment by jacklandrin** [comment]
@Similarityoung 感谢反馈。 你可以在OnlySwitch的设置中找到Evolution选择。请使用里面的Hide Desktop Icons来隐藏桌面，不要使用自定义里的隐藏桌面，你将不会遇到你说的问题。

**Comment by Similarityoung** [comment]
不知道为什么，我使用 Evolution 里的Hide Deskop Icons按钮无法隐藏桌面图标，按下按钮没有任何反应。。。

**Comment by jacklandrin** [comment]
那个按钮对应的是系统设置里的这个选项，你可以检查一下
<img width="713" alt="Screenshot 2024-03-14 at 11 52 57" src="https://github.com/jacklandrin/OnlySwitch/assets/3782279/32e21b15-ee2e-4969-8f65-d530d1fd16bf">

**Comment by Similarityoung** [comment]
<img width="691" alt="image" src="https://github.com/jacklandrin/OnlySwitch/assets/94664304/3cac2156-a089-47e3-8028-a78122e81c6a">

确实可以对应系统设置的按钮，但是按钮并不会控制桌面隐藏程序，是因为我处于台前调度的状态吗

**Comment by jacklandrin** [comment]
如果处于台前调度状态，控制隐藏桌面的是我截图里红框右边的那个选项。目前OnlySwitch里没有开关来控制它，不过可以考虑加一个，只是这个开关的名字不太好取，会比较长

**Comment by Similarityoung** [comment]
哈哈哈，确实
