### ISSUE TITLE
Natural Scrolling Switch

### ISSUE THREAD

**Issue by cnrblm** [jacklandrin/OnlySwitch#126]
While I want to use the trackpad, I enable the natural scrolling feature. However, I disable the natural scrolling feature because I generally use a mouse. It is a good feature for me and others who use their Macs like me.

**Comment by jacklandrin** [comment]
Hi @cnrblm ,
In OnlySwitch Shortcuts Gallery, you can find invert scroll direction shortcut to meet your requirement.
