### ISSUE TITLE
does not open

### ISSUE THREAD

**Issue by arturasvlt** [jacklandrin/OnlySwitch#136]
Hi. I have just tried the app. I downloaded it, installed it and it simply does not open. What may be the reason?

**Comment by sagieinav** [comment]
Same for me here. Just downloaded the app, and it just won't open. Tried killing the process and reopening. Also tried installing manually and installing via Homebrew.

**Comment by jacklandrin** [comment]
@arturasvlt @sagieinav Thanks for the feedback. Can you double-check if the only switch icon hidden by notch on menu bar? Because the new icons are always shown on the very left, maybe you need to remove some icons on menu bar. 
Or some apps have conflicts with only switch, such as the issues like this: https://github.com/jacklandrin/OnlySwitch/issues/132#issuecomment-2212396145

**Comment by arturasvlt** [comment]
Hi @jacklandrin. Thanks for a quick response. I have connected the mac to external displays and it seems its actually working.. However, when I am only with the macbook with no other displays, I cannot see the menu bar icon, maybe it's under the black notch as you say. But I see there is some option to hide menu bar icons which would maybe help. I have this feature enabled and see another icon with two circles in the menu bar, but it doesn't seem to hide anything.

**Comment by jacklandrin** [comment]
@arturasvlt Can you check the settings for Hide menu bar icon? There's an introduction to how to use it. It would help if you moved the icon to some icons' left which need to be hidden.

**Comment by arturasvlt** [comment]
> @arturasvlt Can you check the settings for Hide menu bar icon? There's an introduction to how to use it. It would help if you moved the icon to some icons' left which need to be hidden.

thank you! Worked :)

**Comment by kauelima** [comment]
Same issue for me, using only my macbook display nothing showed, but going into my external monitor it worked. Maybe upon start the app is putting itself inside of the "Hide menu bar icons?"
