### ISSUE TITLE
开启背景噪音无声音

### ISSUE THREAD

**Issue by bugMaker404-yc** [jacklandrin/OnlySwitch#137]
<img width="480" alt="问题" src="https://github.com/jacklandrin/OnlySwitch/assets/71744951/32dac13a-9c8c-428b-83fb-63489c74f59a">

**Comment by qq734556338** [comment]
macbook pro m2  系统版本13.6.3

**Comment by jacklandrin** [comment]
背景噪音需要从GitHub上缓存下来，可能有时国内网络受限，所以下载失败
