### ISSUE TITLE
Dead on M3 Pro Sonoma

### ISSUE THREAD

**Issue by ActualAkshay** [jacklandrin/OnlySwitch#140]
**Describe the bug**
Nothing happens on right or left clicking the Menubar icon after installation on MacBook Pro M3 Pro, MacOS Sonoma 14.5 (23F79)
**Expected behavior**
Menu should open.

**Screenshots**
![CleanShot 2024-07-17 at 05 59 35](https://github.com/user-attachments/assets/9d0e2831-b7e6-4c0d-982d-3e5ca540cce7)

**Comment by Willygoat1** [comment]
You are clicking the incorrect icon. That icon hides menu bar items, hold command and slide that icon to hide/unhide items.

**Comment by ActualAkshay** [comment]
Yeah it was pretty confusing. The main icon appeared after 100 times trying what you just said

> You are clicking the incorrect icon. That icon hides menu bar items, hold command and slide that icon to hide/unhide items.
