### ISSUE TITLE
“置顶便签”按键无法出现 "Top Sticker"button doesn't show

### ISSUE THREAD

**Issue by suibianzai** [jacklandrin/OnlySwitch#141]
**Describe the bug**
列表无法显示“置顶便签”的按钮

**To Reproduce**
1. 进入“设置”-“自定义”
2. 勾选“置顶便签”
3. 关闭设置页面，点击右上角onlyswitch图标，跳出列表，里面没有出现“置顶便签”的选项，但快捷键可以生效
4. 重启无效

**Screenshots**
<img width="1217" alt="截屏2024-07-28 00 05 53" src="https://github.com/user-attachments/assets/92f8114a-f76a-41e9-8e0d-eb07bed004e5">

**Desktop (please complete the following information):**
 - OS: macOS Monterey12.6.1

**Additional context**
快捷键置顶便签只对系统自带的“备忘录.app”生效，对“便笺.app”不生效。

*我是昨天刚刚开始使用onlyswitch的新用户，偶然从B站上得知这款app，只使用了一天就感觉相见恨晚。因为只有onlyswitch通过这么建德的一个操作就能完成我“置顶笔记”的需求。作为ADHD，我要置顶的笔记是用来记录当天的top priorities，以起到随时提醒我回归注意力。今天用了一天onlyswitch，感觉使用电脑时的目标性强了很多~十分感谢作者大大🙏🏻🙏🏻🙏🏻
许愿后续能够支持“置顶便笺app”（屏幕占用更小）😄

**Comment by jacklandrin** [comment]
便签不能显示的原因是我把他在macOS 13以下的系统里屏蔽了，因为我调用了一个macOS 12里还不支持的接口。但是我依然很好奇，为什么快捷键可以给他显示出来

**Comment by jacklandrin** [comment]
我是没有计划去支持macOS12的，因为会有系统的bug导致UI有问题。所以，建议升级到macOS 13。

**Comment by suibianzai** [comment]
> 我是没有计划去支持macOS12的，因为会有系统的bug导致UI有问题。所以，建议升级到macOS 13。

好吧 知道了 谢谢~
