### ISSUE TITLE
[interface] some ideas and suggestions

### ISSUE THREAD

**Issue by despecial** [jacklandrin/OnlySwitch#16]
First up, great piece of software - very helpful.
Since it is growing quickly, I was thinking about how the usage might be a problem with more and more toggles.
So I played around a bit, tried to group them somehow and used two columns, so that the open menu is not too high.
It's just a suggestion, copy & paste, nothing special. Keep up the good work!

![onlyswitch](https://user-images.githubusercontent.com/4135109/149429703-d1b43a33-fe58-4e1f-8dcc-1329db4743cb.png)

**Comment by jacklandrin** [comment]
Thank you for the nice design! It looks better than current UI. But I have to consider how to re-order items on this UI. Besides, if users just prefer to show few items. This design can be viewed as an alternative option, when exceed a certain amount of items be displayed. I'll think about how to blend your design to current actual demands.

**Comment by despecial** [comment]
Sure, you are welcome. I was just playing around. The grouping is a way to let the user quickly (re-)find the desired option.
If it helps you, I am glad. Looking forward to see the development of the app.

**Comment by jacklandrin** [comment]
Since version 2.2, only switch supports two columns.
