### ISSUE TITLE
what does the 'Xcode Derived Data' mean?

### ISSUE THREAD

**Issue by dvdong** [jacklandrin/OnlySwitch#3]
Hi, i want to know what will happen when i switch the 'Xcode Derived Data' option? Thank you

**Comment by jacklandrin** [comment]
Delete Deriveddata folder. When you open Xcode again, it will make a new empty folder automatically. You can check the code.

**Comment by tristanSIF** [comment]
i think we can use a "Clean" button instead of a switch.

**Comment by jacklandrin** [comment]
> i think we can use a "Clean" button instead of a switch.

No problem

**Comment by jacklandrin** [comment]
> i think we can use a "Clean" button instead of a switch.

I have used button instead of switch on version 1.3. Try the new one.
