### ISSUE TITLE
Design-Refinement of OnlySwitch

### ISSUE THREAD

**Issue by macx** [jacklandrin/OnlySwitch#33]
Thanks for this very helpful tool. I would love to see some design refinement, to make it more beauty.

- Just by adding padding to the labels, decreasing the padding at the pane borders and the toggles, it's much cleaner in design.
- Please remove (the hideous and huge) Ad for your other apps. If you like, add it to the menu of your app.
- Combining the left arrangement icon and the settings icon would help to differentiate both buttons.
- Move settings button as an option in the app menu bar.
- Remove the name and version number of the app windows because we all know the name, the version number could sit in the menu bar.

I have made a quick photoshop mockup for you to understand my concerns. Without chancing icon or text size, it's much more compact and hopefully looks better.

<img width="904" alt="only-switch-design-refinement" src="https://user-images.githubusercontent.com/84112/165935558-757cde0d-14ca-46e6-9f30-ae139705e085.png">

Would love to see the changes in reality!

**Comment by jacklandrin** [comment]
Thank you for the nice design. I'll consider your suggestion.
