### ISSUE TITLE
希望可以支持屏幕锁定和键盘锁定功能

### ISSUE THREAD

**Issue by rader124124** [jacklandrin/OnlySwitch#34]
安利了身边所有的朋友从One Switch转到Only Switch，
美中不足的是缺少One Switch的「屏幕清洁」功能，
希望作者可以增加屏幕锁定和键盘锁定功能，
方便强迫症患者每天清理屏幕和键盘

**Comment by jacklandrin** [comment]
十分感谢您的支持，我会考虑的

**Comment by jacklandrin** [comment]
@rader124124 屏幕检测功能已上线2.3版本，可以用来当屏幕清洁用
