### ISSUE TITLE
media keys for radio

### ISSUE THREAD

**Issue by WladyX** [jacklandrin/OnlySwitch#36]
would it be possible to implement the media keys control for radio? play/pause?
thank you for this great app!

**Comment by jacklandrin** [comment]
Thx for your good suggestion. I'll consider adding this feature.

**Comment by jacklandrin** [comment]
@WladyX I've researched some solutions, listening media keys to control will conflict with Apple Music and web video. So before I finding better way, the temporary solution is that you can set other hot keys for radio.

**Comment by jacklandrin** [comment]
@WladyX I know how to figure out it now.

**Comment by WladyX** [comment]
Cool, you can also get inspiration from this project i think:
https://github.com/SokoloffA/radiola

**Comment by jacklandrin** [comment]
@WladyX yes, I just added `togglePlayPauseCommand` target to `MPRemoteCommandCenter`, then I found it works. Now I try to add next/previous feature for radio, like this you can change stations in your list by media keys. All feature will release in version 2.3.3.

**Comment by jacklandrin** [comment]
@WladyX version 2.3.3 has released.

**Comment by jacklandrin** [comment]
@WladyX You can check your control center to see which player is prior. The media keys only control the prior player. In macOS, the latest opened player will be the prior player.

**Comment by WladyX** [comment]
Radiola does not even show up in control center. I see ony onlyswitch there.
Anyway, I've closed both, reopened oneswitch, still does not work :)

**Comment by jacklandrin** [comment]
radiola's solution is listening the keyboard, that will conflict with other player in control center's now playing. When press play button, perhaps, radiola and other player play sound in same time. But in your case, I suggest you can check if now playing function works. You can open a Youtube video, then press media keys to test if it works.

**Comment by WladyX** [comment]
I cannot control youtube from the media keys it seems...

**Comment by jacklandrin** [comment]
I'm not sure whether it's a bug of macOS. I developed this feature on macOS 12.4 and also tested it on 13.0. You can try to restart Mac. If your macOS is old version(less than 12.4), you can try to upgrade it.

I found that similar issue is reported in macrumors forum.
https://forums.macrumors.com/threads/now-playing-on-menu-bar-issue.2333647/

I hope it's useful for you.

**Comment by WladyX** [comment]
I found this thread:
https://www.reddit.com/r/MacOS/comments/knwj84/media_keys_and_control_center_apple_music_do_not/
and tried `launchctl load -w /System/Library/LaunchAgents/com.apple.rcd.plist` and this solved my issue, now onlyswitch media keys work!
Thank you so much for helping with this!

**Comment by WladyX** [comment]
I'm pretty sure I disabled that service in order to get rid of Music app when i connected my headphones :))
