### ISSUE TITLE
Radio change notification

### ISSUE THREAD

**Issue by WladyX** [jacklandrin/OnlySwitch#40]
I think it would be useful to display the radio name when you change it (by next/previous media keys).
Thank you!

**Comment by jacklandrin** [comment]
good idea! I wanna add a notification when song title change as well.

**Comment by WladyX** [comment]
Maybe the song title should be configurable, it could become distracting :)

**Comment by jacklandrin** [comment]
Sure. For all notification functions I will add settings options.
