### ISSUE TITLE
Hide Menu Bar Icon not showing the | in menu bar

### ISSUE THREAD

**Issue by akshilshah** [jacklandrin/OnlySwitch#41]
**Describe the bug**
Functionality - The hide menu bar icon is not loading " | " in the menu bar. Due to this, it makes impossible to use this feature.

**To Reproduce**
1. Go to OnlySwitch Preference
2. Navigate to ```Hide Menu Bar Icon``` setting
3. Click on Enable

**Expected behavior**
It should show" | " in the menu bar

**Desktop (please complete the following information):**
 - OS: macOS Monterey Version 12.4
 - OnlySwitch Version 2.3.3

**Comment by jacklandrin** [comment]
Because the initial location of the vertical bar is on the far left, you might not see it when there are too many icons and menus. So, you can check if it's this situation. Meanwhile, please confirm the switch is off.

**Comment by akshilshah** [comment]
It worked thanks.
