### ISSUE TITLE
Clear DNS Cache

### ISSUE THREAD

**Issue by nomadjimbob** [jacklandrin/OnlySwitch#43]
I regularly need to clear the DNS cache on the Mac by using terminal commands or a program like CleanMyMac. It would be great if this app had an option to do this within the _Cleanup_ section along side the XCode Derived Data option.

These are the typical terminal commands that need to be run to perform this clearing:

* For macOS High Sierra and later - `sudo killall -HUP mDNSResponder`
* For macOS El Capitan - `sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder`

**Comment by jacklandrin** [comment]
@nomadjimbob Thank you for the suggestion. I think a shortcut action may meet your demand. You could share the shortcut to the shortcuts gallery in OnlySwitch. It's easier to publish, everyone can get this feature without a new release. 
Learn about how to contribute shortcuts to the gallery:
https://github.com/jacklandrin/OnlySwitch/blob/main/ShortcutsGalleryContributing.md

**Comment by jacklandrin** [comment]
If you couldn't contribute to it, I can share it from me.

**Comment by nomadjimbob** [comment]
I ended up setting it up by shortcut which works great. I'm happy to add it in through a PR.

Just noticed, 09cb781f40b2736ca8dc1ecd540ce95db39390ff moved the location of ShortcutsMarket.json to `/OnlySwitch/Resource/ShortcutsMarket/ShortcutsMarket.json`. The documentation you linked still has it listed at `/OnlySwitch/ShortcutsMarket/ShortcutsMarket.json`. If you can let me know which is correct and I can go from there.

**Comment by jacklandrin** [comment]
/OnlySwitch/Resource/ShortcutsMarket/ShortcutsMarket.json is correct. You can fetch my newest code, then pull request.

**Comment by jacklandrin** [comment]
I've merged your pr, but I find a bug of mine. I moved the location of ShortcutsMarket.json, but I didn't modify the URL of the request this JSON. I'll fix it in version 2.3.4.

**Comment by jacklandrin** [comment]
2.3.4 is released.
