### ISSUE TITLE
Settings dialogue behind main window / radio icon always shown

### ISSUE THREAD

**Issue by despecial** [jacklandrin/OnlySwitch#45]
It's probably not a real bug - just not ideal
Using 2.3.4 on MacOS Monterey 12.2

1.) Activating the settings will open the window behind the main window. This should be vice versa
2.) I do not use the radio but the player symbol is always shown in my menu bar - how to disable this?

Thanks!

**Comment by despecial** [comment]
Thanks for the response

1.) I would simply suggest that the settings window should always be above the main window (if thats open, or close it)
2.) I do not see that option and why isnt it a toggle in the app? :D
<img width="875" alt="Bildschirmfoto 2022-07-13 um 19 44 09" src="https://user-images.githubusercontent.com/4135109/178797399-423b0d51-0a74-4790-85cc-0ab0447e6240.png">

**Comment by despecial** [comment]
@jacklandrin thanks for the headsup. I think something is wrong with the last update.
The option is set to show the icon when active. But its not and the radio is disabled in OpenSwitch.
So it shouldnt be shown.

Since its a system wide setting I want to keep it, because it is also active when using youtube, etc.
It's definately a setting/option which shows the radio play controls.

**Comment by jacklandrin** [comment]
@despecial This feature is actually for media keys control. Once users just run OnlySwitch, can straightly play radio by keyboard. So the player is registered in **Now Playing** after launching, then the icon will display on menu bar.
I understand your demand, and consider adding a toggle for your case in next version. It can manipulate the timing of registering, after launching or after first playing. How do you think the plan?

**Comment by despecial** [comment]
You should only register it WHEN radio is enabled in OnlySwitch.
If its not active, nor should the controls be active/visible.

**Comment by jacklandrin** [comment]
In the **Individuell Einrichten** switches just toggle visible/invisible in popover's list instead of enable/disable. Though a switch is off on this setting, you still can control it via hotkeys. This is why the switch **Menüleistensymbol ausblenden** has an independent enable toggle. I can understand your suggestion, but that violates this common design principle.

**Comment by despecial** [comment]
I believe you mix something up.

As you can see in my screenshot, the radio player is not active but still the play icon is visible in the menu bar
If I go to individual settings and deactivate the radio player completely - the icon still shows up in the menu bar.

Logically, the icon should never be visible if the radio player is not activated.
Not sure what you mean by design principle. THIS is the principle > if nothing is activated, it has no reason to be visible.

**Comment by jacklandrin** [comment]
When the radio player switch is off, it just means pause status. That is like you open Apple Music, and play a song, then pause it. You still can use media key or button on GUI to continue playing. Meanwhile, the now playing show on the menu bar until closing it.
However, if the radio is deactivated and unregister in Now playing at same time, the media keys won't work.  Media keys controlling is the new feature in version 2.3.3(https://github.com/jacklandrin/OnlySwitch/issues/36). 
Unfortunately, Apple doesn't offer a stop status for the control center and now playing, so the symbol is always visible unless you close all players. 
This is why I give you above suggestion. If you never use radio, you can never see OnlySwitch invoke the symbol.

**Comment by despecial** [comment]
Thanks for trying to explain.

As i said before: it still shows up, even if i completely disable the radio option in "Individuell Einrichten". Closed OpenSwitch > the play icon stays in the menu bar and radio is gone but apple music shows up (which is not used by me at all). There is no player to close. 

And what should happen when activating "Spotify" on the individual pages? Because nothing happens when toggling it.

**Comment by despecial** [comment]
Yes, that would be good to have a toggle that actually does what it says ;)

Because right now the use of a toggle for the radio player doesn't really make sense ("When the radio player switch is off, it just means pause status."). A play/pause button would be more accurate and better UX.

> If you have multiple players register in Now Playing, you will see a list of them when tap the symbol. If you kill the prior player's process, the second one will become prior, like a stack.

I understand what you say and OnlySwitch should let the user be in control of what is activated and what not. So a switch to toggle the Radio functionality would be very appreciated.

PS: Spotify is not located under "audio" if its shown in OnlySwitch.

**Comment by jacklandrin** [comment]
I feel Apple intent to avoid the stop status on its ecosystem. Whatever Apple Music or Spotify, only has play and pause two status. Of couse as you said, the play/pause button will be more accurate. I can improve it. I just follow the **Switch** princeple before, actually the clean button and run button haven't been Switch since eariler version. Indeed it perhaps brings some confuse to users. 
The wrong category of Spotify and Apple Music is a bug, I'll fix it in next version.

**Comment by jacklandrin** [comment]
If you would like, join the telegram group. https://t.me/OnlySwitchforMac
I'll release beta version on it, you can experience it to decide to what you want.

**Comment by despecial** [comment]
> BTW, for the question of settings window level. If let settings window above the popover window, settings window will above other apps' windows as well. Could you accept it?

I am not aware how its done on MacOS but as a web developer you work with z-indexes. So if you open the settings, you just could lower the level of the main window: https://jameshfisher.com/2020/08/03/what-is-the-order-of-nswindow-levels/
