### ISSUE TITLE
Date is truncated when "Hide Menu Bar Items"

### ISSUE THREAD

**Issue by YBogomolov** [jacklandrin/OnlySwitch#49]
**Description**
The date is truncated (lost day number and month) when "Hide Menu Bar Items" is enabled.

**To Reproduce**
1. Enable "Hide Menu Bar Items"
2. Observe that the date is truncated
3. Click the date to reveal Notification Center
4. Observe that the highlighted "clicked area" is offset (see screenshots)

**Expected behaviour**
1. Date is not truncated.
2. Clicked area is highlighted correctly.

**Screenshots**
Behaviour when "Hide Menu Bar Items" is enabled:
<img width="565" alt="Screenshot 2022-08-03 at 12 24 29" src="https://user-images.githubusercontent.com/908865/182586765-62b6b8da-299b-4be5-bdf6-14db1ea9f49f.png">

Behaviour when "Hide Menu Bar Items" is disabled:
<img width="480" alt="Screenshot 2022-08-03 at 12 24 44" src="https://user-images.githubusercontent.com/908865/182586777-8cf68d69-b1eb-494a-9d07-ef7a6a791786.png">

**Desktop (please complete the following information):**
 - OS: macOS Monterey v.12.5
 - Browser: Safari v.15.6 (17613.3.9.1.5)
 - Version: v.2.3.5 (build 66)

**Comment by jacklandrin** [comment]
Thank you for the feedback. You can set this on System Preferences -> Dock & Menu Bar to keep the date full.
<img width="780" alt="Screenshot 2022-08-03 at 12 50 49" src="https://user-images.githubusercontent.com/3782279/182591177-05523707-bfe7-4c5a-9c42-6817e823b835.png">

**Comment by YBogomolov** [comment]
Sorry, didn't noticed this wasn't set to "always". New Mac, same problems. Thank you for the quick response and awesome product! 🙏
