### ISSUE TITLE
Can't navi to settings page when hide menu bar icon if only switch icon appear at the left

### ISSUE THREAD

**Issue by BooboNikita** [jacklandrin/OnlySwitch#51]
**Describe the bug**
I turn on the hide menu bar icon switch and where the switch icon appears at the left, then there is a dead lock if the only switch is active and its icon is hidden, so I can't navigate into the setting page and disable the swtich.

**To Reproduce**
1. Put the hide icon tag on the right of the "only switch" icon;
2. Go to settings page and turn on "hide menu bar icon" switch
3. The left icons are hidden including "only switch" icon.

**Expected behavior**
Never hide "only switch" icon.

**Comment by jacklandrin** [comment]
Thank you for the feedback. Which OnlySwitch version are you using?

**Comment by BooboNikita** [comment]
> Thank you for the feedback. Which OnlySwitch version are you using?

2.3.7

**Comment by jacklandrin** [comment]
I can give a workaround to solve the current problem. delete this file  /Users/xxxx/Library/Preferences/jacklandrin.OnlySwitch.plist. Actually, there is logic in the code to avoid this situation. It doesn't happen on my side. I think I need more clue.

https://user-images.githubusercontent.com/3782279/184844089-8c79eb6d-cbc5-4609-b9c6-d0edeb1b1fd2.MOV

**Comment by jacklandrin** [comment]
If you delete plist file, it still can't show the icon, please restart your laptop.

**Comment by BooboNikita** [comment]
> I can give a workaround to solve the current problem. delete this file /Users/xxxx/Library/Preferences/jacklandrin.OnlySwitch.plist. Actually, there is logic in the code to avoid this situation. It doesn't happen on my side. I think I need more clue.
> 
>  IMG_2333.MOV

I recover the hidden icons after I deleted the Userdefaults and some relevant directories. Then I can't reproduce the bug as well. 😂

**Comment by jacklandrin** [comment]
Maybe this problem is caused by cover installation. Some new userdefaults conflict with old settings.

**Comment by jacklandrin** [comment]
Did you update it from 2.3.6?

**Comment by BooboNikita** [comment]
> Did you update it from 2.3.6?

Maybe from 2.3.4 or 2.3.5

**Comment by jacklandrin** [comment]
I tried to install back 2.3.5 and uploaded it to 2.3.7. It still can't reproduce the bug. 🤣
