### ISSUE TITLE
Not working in MacOS Ventura 

### ISSUE THREAD

**Issue by liquidsmok3** [jacklandrin/OnlySwitch#52]
**Describe the bug**
When you run the application, it briefly shows icons in the menu bar and I can also briefly see the settings pane before it all gets hidden.  The application continues to run, but none of its user interface is displayed onscreen and you have to use activity monitor to kill the app.

**To Reproduce**
install the app in MacOS Ventura beta
run the app

**Expected behavior**
Expect to see the user interface for the app

**Screenshots**

https://user-images.githubusercontent.com/105474462/191670493-51fed8d7-6eb3-4ee4-a6fc-c67db9857287.MOV

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Browser: Safari
 - Version: 13.0 beta (22A5352e)

**Additional context**
the app worked in previous builds of Ventura

**Comment by jacklandrin** [comment]
Thank you for the feedback. I still stay at beta 7. Wait for me to update.

**Comment by jacklandrin** [comment]
@liquidsmok3 Can I ask you which version of OnlySwitch you are using? I found another issue in beta 8, that I cannot select settings tab.

**Comment by liquidsmok3** [comment]
> @liquidsmok3 Can I ask you which version of OnlySwitch you are using? I found another issue in beta 8, that I cannot select settings tab.

I’m using the most recent version of only switch 2.3.7. I made sure to download the latest to see if it fixed my issue before I reported it.

**Comment by liquidsmok3** [comment]
Also, I just downloaded the source and built it in Xcode.  Please correct me if im wrong, im still pretty new to swift and ive never actually dug through someone else's code yet, but I got it to run locally without crashing.
There were about 5 issues or so in Xcode, I'll post a screenshot. once I fixed the issues the build was fine and ran mostly fine.  The main app works, but the settings app I couldn't go into other sections in settings. So it mostly seems like it just needs to be built again to fix whatever apple changed in Ventura Beta 8 that broke it.  Im not sure if its ever been built with Xcode 14 beta under Ventura beta which prob isn't a good idea to begin with (I was a forced).  

![33A4FDC3-2E09-44E0-A440-1BDA1952CAA6](https://user-images.githubusercontent.com/105474462/191895829-165c887a-f683-40bd-8061-da2073761f9d.jpeg)
![E43B36A5-5821-4352-A3AC-D968FE24DA8E](https://user-images.githubusercontent.com/105474462/191895831-975ab2ad-ed90-4403-81b1-7bd4eec362e1.jpeg)

**Comment by jacklandrin** [comment]
@liquidsmok3 For the settings issue, I'm not sure this is a bug about NavigationLink in beta 8. I'll try to fix it in 2.3.8 ASAP.

**Comment by romanr** [comment]
I have similar issue on Ventura. 

- The settngs menus are not doing anything. 
- Tehre's an icon in menu bar that looks like `o|o`. Clicking on it does nothing. Perhaps it's from function I can not access due to above issue.

OnlySwtich 2.3.7
Ventura 13.0 Beta (22A5358e)

https://user-images.githubusercontent.com/329079/193522606-1c55ed37-d4a1-434a-934a-a6b3b3aa0032.mov

**Comment by jacklandrin** [comment]
@romanr @liquidsmok3 This is the 2.3.8 beta. It fixed the bug that settings menu doesn't work after ventura beta 8.
[Only Switch.app.zip](https://github.com/jacklandrin/OnlySwitch/files/9698051/Only.Switch.app.zip)

**Comment by liquidsmok3** [comment]
> @romanr @liquidsmok3 This is the 2.3.8 beta. It fixed the bug that settings menu doesn't work after ventura beta 8. The final version will update after Ventura release.
> [Only Switch.app.zip](https://github.com/jacklandrin/OnlySwitch/files/9698051/Only.Switch.app.zip)

Downloaded this 3 times and each time MacOS says "Only Switch.app is damaged and cant be opened.  You should move it to the Trash."

not sure if its the file or something happening to it in transit.

**Comment by liquidsmok3** [comment]
> Oops sorry forgot to report. Everything works fine with beta!On 6 Oct 2022, at 3:59 pm, liquidsmok3 ***@***.***> wrote:﻿ @romanr @liquidsmok3 This is the 2.3.8 beta. It fixed the bug that settings menu doesn't work after ventura beta 8. The final version will update after Ventura release. Only Switch.app.zip Downloaded this 3 times and each time MacOS says "Only Switch.app is damaged and cant be opened. You should move it to the Trash." not sure if its the file or something happening to it in transit. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

so that file works for you ?

**Comment by romanr** [comment]
> so that file works for you ?

Yes 2.3.8 beta fixes the issues!

**Comment by liquidsmok3** [comment]
> > so that file works for you ?
> 
> Yes 2.3.8 beta fixes the issues!

ok, not sure why the zip giving me issues.  I just downloaded the beta source and built it and everything seems to work fine now.

**Comment by jacklandrin** [comment]
The Ventura has been released today. I found that 2.3.7 can normally run on this release.

**Comment by liquidsmok3** [comment]
downloaded the 2.38 official release a few min ago and its still doing the exact same thing in my original post.  I can supply an updated screen recording (and more) if you want.  But the app crashes on start, at least all of its UI does, the app is still running in the task manager and you have to force it to quit as there is no UI.

Ventura 13.1 Beta (22C5050e)

**Comment by jacklandrin** [comment]
@liquidsmok3 I am not sure if it is also a bug for Mac beta version. I will update 13.1 beta 3 to try.

**Comment by liquidsmok3** [comment]
> @liquidsmok3 I am not sure if it is also a bug for Mac beta version. I will update 13.1 beta 3 to try.

im not exactly sure either, but I did fix these issues locally  back in September and Ive been running  my local version ever since without issue on every Ventura beta.  The official releases dont work for me at all.
