### ISSUE TITLE
隐藏菜单栏图标功能无法关闭

### ISSUE THREAD

**Issue by eryajf** [jacklandrin/OnlySwitch#53]
我用的是最新版本。Mac系统为：m1版本的，系统为12.6。

我尝试打开了隐藏菜单栏图标功能，现在关闭了这个功能，但是总会自己又打开，不知道怎么回事儿。

![yincang](https://user-images.githubusercontent.com/33259379/195990665-6dc58bbe-bb1b-4248-9bc0-503e5feb1662.gif)

动图里边，第一次打开是我把他关闭了，第二次打开主界面，可以看到自己又打开了。

**Comment by jacklandrin** [comment]
您好！请确认一下有没有设置定时自动隐藏图标

**Comment by eryajf** [comment]
看到了，的确是这个原因，之前配置了5秒，所以基本上刚好第二次打开又看到恢复了。

现已解决，非常感谢！
