### ISSUE TITLE
Is it possible to hide "Hide menu bar icons"?

### ISSUE THREAD

**Issue by mgthantzin** [jacklandrin/OnlySwitch#54]
Is it possible to hide this icon since I am not using that feature?

![image](https://user-images.githubusercontent.com/137266/196007068-2ab362cc-1ee5-4db0-9400-c6aea9588bf4.png)

**Comment by jacklandrin** [comment]
Yes, of course. Please open the settings window, click Switches Availability on the menu bar, and disable hide menu bar icons.
<img width="516" alt="Screenshot 2022-09-11 at 11 45 20" src="https://user-images.githubusercontent.com/3782279/196007167-10342180-5efe-4f7b-b964-8a5f45904d5e.png">

**Comment by mgthantzin** [comment]
Thanks, Jack! That's a very quick response! Appreciate that.
