### ISSUE TITLE
Typo in menu bar -> Switches Availability

### ISSUE THREAD

**Issue by devasmith** [jacklandrin/OnlySwitch#55]
**Describe the bug**
Clicking on Switches Availability in the menu bar has a typo when option _Hide Menu Bar Icons_ is disabled.
It says: _Enale Hide Menu Bar Icons_

**To Reproduce**
1. Open application
2. Click on Switches Availability

**Expected behavior**
Should say: Enable Hide Menu Bar Icons

**Screenshots**
<img width="192" alt="image" src="https://user-images.githubusercontent.com/60352859/197386937-d3bd9ae8-077a-47ff-9a03-b7bddce6d9a8.png">

**Desktop (please complete the following information):**
 - OS: MacOS 12.6
 - OnlySwitch version: 2.3.7

**Comment by jacklandrin** [comment]
Thank you for the report! I will fix it.

**Comment by jacklandrin** [comment]
Fixed in 2.3.8
