### ISSUE TITLE
report a UI bug of AirPods option

### ISSUE THREAD

**Issue by dvdong** [jacklandrin/OnlySwitch#6]
<img width="343" alt="AirPods" src="https://user-images.githubusercontent.com/36857548/146324916-e99e9e9a-3580-476e-8ce3-8dffb059a9ca.png">

hi, it seems like that there's an overlap of AirPods

**Comment by jacklandrin** [comment]
> <img width="343" alt="AirPods" src="https://user-images.githubusercontent.com/36857548/146324916-e99e9e9a-3580-476e-8ce3-8dffb059a9ca.png">
> 
> 
> 
> hi, it seems like that there's an overlap of AirPods

Which version do you install? I fix this bug in version 1.2

**Comment by dvdong** [comment]
> > <img alt="AirPods" width="343" src="https://user-images.githubusercontent.com/36857548/146324916-e99e9e9a-3580-476e-8ce3-8dffb059a9ca.png">
> > hi, it seems like that there's an overlap of AirPods
> 
> Which version do you install? I fixed this bug in version 1.2

sorry i'm using v1.1, i'll update
