### ISSUE TITLE
Add the possibility to switch the "current" radio station from main menu, instead of going settings

### ISSUE THREAD

**Issue by dylandea** [jacklandrin/OnlySwitch#63]
Hi,

I love Only Switch, and particularly the possibility to easily and simply Play or pause my favourite radio station.
I added 3 radio stations in the settings, and I selected one of the station as my "current" station.

However I am frustrated because I can only play/pause and listen to this "current" station I previously selected on the settings. 
I cannot easily switch between all the stations I saved in the settings.

**Describe the solution you'd like**
I'd love the possibility to switch between radio stations from the main menu where the Radio Switch is available.
In my case, a simple "Next" button, just next to the already available "Play" button, would be enough because I only have 3 stations.

**Describe alternatives you've considered**
I considered looking for another menu bar app which would be specialized in managing radios, just basic functions, web radio stream url, as Only Switch: play/pause, but also a dropdown which would appear for example by right click and permits selecting the radio. Nothing fancy like TuneIn with subscriptions, podcasts, search function, etc...

But I didnt find such app, I looked everywhere, and I am really surprised that Only Switch is the unique app permiting playing web radios.... But too bad I can't change station.
I also asked on Reddit and looked on the menubarapp website, nobody found anything.
So I was hoping to see this function on this app, because unless this, I am qauite happy with the rest of the functions.

**Additional context**
This could also be a good solution: instead of a "Next" button, which is enough for me, but not enough for someone with lots of radio stations, the better would be a dropdown menu, which would show all the station.

Thanks

**Comment by dylandea** [comment]
I just found "My Tuner Radio" on the app store that does it (little icon in the menu bar that permits choosing between favorites list of radios).
But the app is overkill, a lot of options, categories, radios, and a bit laggy.

And instead of just OnlySwitch, I have now 2 apps, while the reason for having OnlySwicth is to only have "one" switch to rule them all !

**Comment by jacklandrin** [comment]
@dylandea Thank you for the feedback. 
MacOS supports Now Playing and Control Center, so technically you can change next station by them. If you keyboard has media keys, you also can press them to control the radio station.
<img width="367" alt="Screenshot 2022-12-19 at 17 54 28" src="https://user-images.githubusercontent.com/3782279/208478488-0a319f16-f124-4d9d-95a2-1e478b43f89b.png">
<img width="313" alt="Screenshot 2022-12-19 at 17 53 54" src="https://user-images.githubusercontent.com/3782279/208478387-c38779b4-004f-4b52-aa95-7ef658f26583.png">

**Comment by dylandea** [comment]
No way...
I'll try when I get home, and if it works, you're really a legend !
Thanks for your fast reply.

**Comment by dylandea** [comment]
It works as you said !
Thanks
