### ISSUE TITLE
Keyboard shortcuts not working for some swicthes

### ISSUE THREAD

**Issue by WladyX** [jacklandrin/OnlySwitch#68]
If if set a keyboard shortcut for Mute or Show hidden files it works as expected, but if i set a shortcut for Radio or for a MacOS Shortcut it does not work.

**Comment by BoscoDomingo** [comment]
Same here, thought I was going insane for a bit! 😂 Hopefully a fix can be rolled out soon

**Comment by BoscoDomingo** [comment]
I have just checked and this issue can be closed as it is solved @WladyX

**Comment by WladyX** [comment]
yup, works for me also, closing, thanks @jacklandrin!
