### ISSUE TITLE
Please update icons

### ISSUE THREAD

**Issue by beniamin20** [jacklandrin/OnlySwitch#7]
Use vector icons, (PDF) so the icon's won't be shady on higher resolution

ex:
![Screenshot 2021-12-18 at 10 05 49](https://user-images.githubusercontent.com/12484142/146634251-167e0902-d183-49f1-98f1-a39674a48aac.png)
![Screenshot 2021-12-18 at 10 05 59](https://user-images.githubusercontent.com/12484142/146634258-43bfaf89-61d8-4b11-8c43-b5ab48e44804.png)

**Comment by jacklandrin** [comment]
> Use vector icons, (PDF) so the icon's won't be shady on higher resolution
> 
> ex: ![Screenshot 2021-12-18 at 10 05 49](https://user-images.githubusercontent.com/12484142/146634251-167e0902-d183-49f1-98f1-a39674a48aac.png) ![Screenshot 2021-12-18 at 10 05 59](https://user-images.githubusercontent.com/12484142/146634258-43bfaf89-61d8-4b11-8c43-b5ab48e44804.png)

Thank you for your feedback!

These icons are SF Symbols, so they are vector image. Just I use NSImage to store them, and don't resize them(The sizes are small in default). When I set them in Swift's Image and resize, the small images are enlarged, so they look like some blur.

I've fix this bug in version 1.4. You can download the new version now.
