### ISSUE TITLE
电台增加切换电台的功能

### ISSUE THREAD

**Issue by jwj1648** [jacklandrin/OnlySwitch#72]
在播放电台时，希望能够像切歌一样可以切换到下个电台。
目前导入电台时，如果导入的数量比较大的话，配置页面会长时间loading，卡死。

**Comment by jacklandrin** [comment]
@jwj1648 
1.当OnlySwitch作为最后活跃的播放器时，你是可以通过键盘媒体键里上一曲/下一曲切换电台的，或者使用控制中心切换。
2.请问你一次性倒入了多少个电台？
