### ISSUE TITLE
Order icons (two columns display) + Night shift level

### ISSUE THREAD

**Issue by ertabzh** [jacklandrin/OnlySwitch#73]
Hello, congratulations for your application ! 
Just 2 things I can't figure out:
- Possibility of manually sorting the location of the icons when the display in double columns has been chosen.
- Night shift: when activated, the function affects a very strong night shift close to 100%. Why does it not take into account the Night Shift setting defined in the device settings?
Thank you.

**Comment by jacklandrin** [comment]
@ertabzh Thank you for your feedback. 
Regarding sorting items in double columns, I don't have a good design to implement it yet. Current idea and design is contributed by a user. I will reach out to him and try to find out a way.
Adjustable Night shift is a good idea, I will add it to my to-do list.

**Comment by ertabzh** [comment]
Hello, heard, thank you for your feedback.

Sincerely.

**Comment by jacklandrin** [comment]
@ertabzh Night Shift settings have been implemented in beta 2.4.1. Please check it. https://github.com/jacklandrin/OnlySwitch/releases/tag/pre-release_2.4.1
