### ISSUE TITLE
 Hi, please add switch to turn on/off "True Tone" option in the display. It's beneficial for photographer/editor when editing artwork to have accurate color when True Tone is off. Thank you!!

### ISSUE THREAD

**Issue by room216** [jacklandrin/OnlySwitch#77]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by room216** [comment]
Hi, please add switch to turn on/off "True Tone" option in the display. It's beneficial for photographer/editor when editing artwork to have accurate color when True Tone is off. Thank you!!

**Comment by jacklandrin** [comment]
Hi @room216 ,
Sorry for reply late. True Tone switch will be integrated in version 2.4.5

**Comment by jacklandrin** [comment]
This feature is integrated with version 2.4.5.
