### ISSUE TITLE
Missing Menu Titles

### ISSUE THREAD

**Issue by kadirermantr** [jacklandrin/OnlySwitch#81]
The titles of the following menus are displays as **SettingsWindow**. They should be displayed as their own names.

- Keep Awake
- Dim Screen
- Back Noises

![image](https://github.com/jacklandrin/OnlySwitch/assets/45540321/5b5dc432-91cc-4428-913a-d1b8180c4e94)

_macOS v13.3.1_

**Comment by jacklandrin** [comment]
Thank you for your feedback! it will be fixed.

**Comment by jacklandrin** [comment]
fixed in version 2.4

**Comment by jacklandrin** [comment]
fixed in version 2.4

**Comment by kadirermantr** [comment]
> fixed in version 2.4

Thank you @jacklandrin 🙌
