### ISSUE TITLE
Custom icons for Evolution shortcuts editor

### ISSUE THREAD

**Issue by piersandro** [jacklandrin/OnlySwitch#84]
**Is your feature request related to a problem? Please describe.**
I would like to be able to set custom icons for switches created with the Evolution Editor perhaps based on the code of the free Font Awesome icons or similar icon sets.

**Describe the solution you'd like**
Add a field in which you can enter the icon code of the selected font set to display a customised icon and not the same one for each button or select from a preview of icons available.

**Describe alternatives you've considered**
Alternative icon set as TrueType Font:
https://fonts.google.com/icons
https://fontawesome.com/icons
https://lineicons.com/icons/
https://pictogrammers.com/library/mdi/

**Comment by jacklandrin** [comment]
Hi @piersandro ,
Thank you for your ideas! Actually, I have the same plan, just don't have proper sources. I think you offer me a lot of awesome icons. I will implement this feature in 2.4.1 or 2.4.2.

**Comment by jacklandrin** [comment]
feature Icons for evolution has been included in version 2.4.1, but I use apple SF symbol in this version.
