### ISSUE TITLE
Two columns view lacks Evolution shortcuts

### ISSUE THREAD

**Issue by piersandro** [jacklandrin/OnlySwitch#86]
**Describe the bug**
When I enable Two columns view my Evolution shortcut disappear.

**To Reproduce**
1. Create at least one Evolution shortcut
2. Go to OnlySwith General Settings'...'
3. Enable Two Columns view
4. Click on OnlySwitch icon in the menu bar
5. See that the Evolution shortcut is missing

**Expected behavior**
I should also see the button in two columns view

**Screenshots**
Single column
<img width="402" alt="Screenshot 2023-06-22 alle 15 07 04" src="https://github.com/jacklandrin/OnlySwitch/assets/19996309/d6b1def9-dbf5-4ca8-a723-70db0b49a288">

Two columns
<img width="692" alt="Screenshot 2023-06-22 alle 15 07 16" src="https://github.com/jacklandrin/OnlySwitch/assets/19996309/7709567a-ef58-4aa1-a10a-b311fcb72436">

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 
 - Version 14.0 (23A5276g)

**Comment by jacklandrin** [comment]
@piersandro Evolution in the dual column mode will be involved in 2.4.1

**Comment by piersandro** [comment]
Thank you! It works.
