### ISSUE TITLE
Feature Request: Low power mode battery 

### ISSUE THREAD

**Issue by Zedris** [jacklandrin/OnlySwitch#9]
would love a way to enable low power mode from a switch in the new mac os update thats available instead of having to go to the battery menu in settings. shortcuts wont do it.

**Comment by jacklandrin** [comment]
> would love a way to enable low power mode from a switch in the new mac os update thats available instead of having to go to the battery menu in settings. shortcuts wont do it.

It's easy to implement. Just it'll request password every toggling. I think it's not elegant. If you can accept it, I'd like to add it.
