### ISSUE TITLE
Pomodoro timer Feature request

### ISSUE THREAD

**Issue by ipiiia** [jacklandrin/OnlySwitch#91]
Can you add a separate menu bar icon for Pomodoro timer?
I'm nervous if I can't check the time of the timer.
It would be great if the remaining time of the timer is displayed in the menu bar.

Thank you for creating a great app
(I'm using a translator)

**Comment by jacklandrin** [comment]
Hi,
Thanks for this idea!
To be honest, I don't want to occupy more space in menu bar. But I understand your requirement, perhaps I will consider to create an interactive widget for this feature on Sonoma, then you can put it on you desktop.

**Comment by ipiiia** [comment]
Thank you for listening to my opinion!
