### ISSUE TITLE
Microphone input indicator in MacOS Sonoma

### ISSUE THREAD

**Issue by devasmith** [jacklandrin/OnlySwitch#94]
**Describe the bug**
Icons on the left side of hide menu bar icons should be hidden.

**To Reproduce**
Drag the microphone indicator to the left side of the hide menu bar icons icon and click Hide Menu Bar Icons.

**Expected behavior**
It should hide the icon.

**Screenshots**
![Screenshot 2023-10-27 at 08 27 53](https://github.com/jacklandrin/OnlySwitch/assets/60352859/4b07e5ae-9182-4790-adcf-fdca8b9d5393)

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.1

**Comment by jacklandrin** [comment]
Hi @devasmith 
The icons of the system permission usage tip cannot be hidden, such as voice input, camera, capture screen usage. This is for security reasons.

**Comment by devasmith** [comment]
> Hi @devasmith The icons of the system permission usage tip cannot be hidden, such as voice input, camera, capture screen usage. This is for security reasons.

Ah that is true. Thanks for the quick feedback!
