### ISSUE TITLE
Night Shift is reverting Mac OS System Settings when Toggled On/Off

### ISSUE THREAD

**Issue by rabbly** [jacklandrin/OnlySwitch#98]
**Describe the bug**
When toggling the Night Shift mode on/off it resets the Night Shift strength in the Mac OS System Settings.

**To Reproduce**
1. Check your Night Shift settings in Mac OS and make sure < 0% (Settings > Displays > Night Shift)
2. Check your Night Shift settings in OnlySwitch and make sure < 0%
3. Toggle on Night Shift in Only Switch
4. Toggle off Night Shift in Only Switch
5. Check your Night Shift settings in Mac OS
>>> You will see they have reverted to 0% (see screenshot below)

**Expected behavior**
I expect the Night Shift settings to remain unchanged in System Settings so that the next time it gets to Sunset Night Shift will work automatically.

**Screenshots**
<img width="470" alt="image" src="https://github.com/jacklandrin/OnlySwitch/assets/2348746/3c33c702-c9cd-43c6-8038-9ed204aeaa19">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: M1 Macbook Pro
 - OS: Sonoma
 - Version v2.4.5

**Comment by jacklandrin** [comment]
Thanks for your feedback! It will be fixed in next version.
