### ISSUE TITLE
可否增加打开 app 的快捷键

### ISSUE THREAD

**Issue by qq3450095290** [jacklandrin/OnlySwitch#99]
我日常使用 “防止锁屏” 这个开关，因此设置了快捷键 command + Y。但是因为没有打开状态栏的 Only Switch app 快捷键，需要点击 app 图标才能打开看到列表（才能看到 “防止锁屏” 开关是否被打开/关闭）。因此原本希望通过快捷键便捷操作 “防止锁屏” 开关，此时因需要点击图标再次查看列表以确认开关是否起效，增加了额外操作。因此想询问作者，是否考虑增加打开 app 以显示开关列表的快捷键，谢谢

**Comment by jacklandrin** [comment]
从2.4.5开始，在设置->通用里有一个叫显示开关列表的快捷键设置，你可以自己设定你想要的快捷键。另外，如果你在系统设置里允许OnlySwitch开启通知功能，每次使用快捷键切换开关时，你会在通知中心看到推送来判断开关的状态

**Comment by qq3450095290** [comment]
问题已解决，感谢作者回复
